"""Add indexes on project_id and created_at for performance

Revision ID: 50f3b241f370
Revises: cfd4f523ede5
Create Date: 2026-01-28 00:10:57.780631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50f3b241f370'
down_revision = 'cfd4f523ede5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_project_items_project_id'), 'project_items', ['project_id'], unique=False)
    op.create_index(op.f('ix_projects_created_at'), 'projects', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_created_at'), table_name='projects')
    op.drop_index(op.f('ix_project_items_project_id'), table_name='project_items')
    # ### end Alembic commands ###
